### ISSUE TITLE
Question about AllGattCharacteristics.java

### ISSUE THREAD

**Issue by dakhnod** [sam016/phonebook-beg-ui#9]
Hi,

I found the characteristic "org.bluetooth.characteristic.digital_output" in your AllGattCharacteristics.java.
Now I am wondering, where you found all of that info, in particular the digital_output.

Sorry for abusing this repository to ask my question.

**Comment by sam016** [comment]
@dakhnod Hi. Sorry about the delay in reply, I had my email notifications off.

I prepared that list around June 3, 2018, by referring to https://www.bluetooth.com/specifications/gatt/characteristics.
It seems that, since then, the specification has changed and they have removed the "digital_output" from characteristics.

If you refer to https://www.bluetooth.com/specifications/specs/?status=all&keyword=GSS&filter=, you would find that the GATT specification from 2017 (which, I believe, I must have used to compile this list during 2018) has been withdrawn and can't be accessed anymore.

Sorry, I can't be of much help around this.
